CREATE TABLE YearGroup(
	Id INT IDENTITY(1,1) NOT NULL,
	Year INT NOT NULL,
	SchoolId INT NOT NULL,

	CONSTRAINT PK_YearGroup
		PRIMARY KEY(Id),
	CONSTRAINT FK_YearGroup_School
		FOREIGN KEY(SchoolId) REFERENCES School(Id)
		ON DELETE CASCADE
);