CREATE TABLE Class(
	Id INT IDENTITY(1,1) NOT NULL,
	Name VARCHAR(10) NOT NULL,
	YearGroupId INT NOT NULL,

	CONSTRAINT PK_Class
		PRIMARY KEY(Id),
	CONSTRAINT FK_Class_YearGroup
		FOREIGN KEY(YearGroupId) REFERENCES YearGroup(Id)
		ON DELETE CASCADE
);