CREATE TABLE School(
	Id INT IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(150) NOT NULL,
	AddressId INT NOT NULL,

	CONSTRAINT PK_School
		PRIMARY KEY(Id),
	CONSTRAINT FK_School_Address
		FOREIGN KEY(AddressId) REFERENCES Address(Id)
);